# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170606_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 6, 6, 17, 35, 56, 191165, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Citizen')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 17, 35, 56, 190534, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Issue'),
        ),
    ]
