# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170606_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
