# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170607_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
